from datetime import UTC, datetime

from market_evolver.expert.schemas import ExpertDefinition, ExpertStatus, Horizon

ALL_TOOLS = (
    "get_company_context",
    "get_fundamentals",
    "get_filings",
    "get_events",
    "get_policy_actions",
    "get_macro_trends",
    "get_fused_claims",
    "get_source_reputation",
    "get_geopolitical_events",
    "get_market_history",
    "get_mechanism_paths",
    "get_backtest_results",
)
FORBIDDEN = (
    "paper_order",
    "risk_policy_mutation",
    "broker_access",
    "expert_creation",
    "topology_mutation",
    "raw_social_instructions",
)
HORIZONS = tuple(Horizon)
CREATED = datetime(2025, 1, 1, tzinfo=UTC)


def _expert(
    expert_id: str,
    name: str,
    domain: str,
    entity_types: tuple[str, ...],
    source_classes: tuple[str, ...],
    tools: tuple[str, ...],
    mechanisms: tuple[str, ...],
    geography: tuple[str, ...] = ("IL", "global"),
) -> ExpertDefinition:
    return ExpertDefinition(
        expert_id,
        name,
        domain,
        geography,
        HORIZONS,
        entity_types,
        source_classes,
        tools,
        (
            "evidence_summarization",
            "contradiction_identification",
            "hypothesis_generation",
            "mechanism_extraction",
        ),
        mechanisms,
        FORBIDDEN,
        f"expert-{domain}/1",
        "explicit-provider-policy:v1",
        CREATED,
        ExpertStatus.EVALUATION,
        ("reviewed-fixed-seed:v0.18",),
        1,
    )


FIXED_EXPERTS = (
    _expert(
        "expert.general",
        "General Market Researcher",
        "general",
        ("company", "country", "sector", "currency", "event"),
        ("official", "filing", "trusted_news", "fused_claim"),
        ALL_TOOLS,
        ("currency_translation", "financing_cost", "risk_premium", "consumer_demand"),
    ),
    _expert(
        "expert.technology_ai",
        "Technology / AI Expert",
        "technology_ai",
        ("company", "sector", "industry"),
        ("official", "filing", "trusted_news"),
        (
            "get_company_context",
            "get_fundamentals",
            "get_filings",
            "get_events",
            "get_policy_actions",
            "get_market_history",
            "get_mechanism_paths",
            "get_backtest_results",
        ),
        ("cloud_capex", "semiconductor_cycle", "customer_concentration", "regulatory_exposure"),
    ),
    _expert(
        "expert.israel_real_estate",
        "Israeli Real Estate Expert",
        "israel_real_estate",
        ("company", "sector", "country"),
        ("official", "filing", "government", "trusted_news"),
        (
            "get_company_context",
            "get_fundamentals",
            "get_filings",
            "get_events",
            "get_policy_actions",
            "get_macro_trends",
            "get_mechanism_paths",
            "get_backtest_results",
        ),
        ("financing_cost", "credit_demand", "construction_labor", "input_cost", "housing_demand"),
        ("IL",),
    ),
    _expert(
        "expert.banking_macro",
        "Banking & Macro Expert",
        "banking_macro",
        ("company", "bank", "country", "currency", "macro_series"),
        ("official", "filing", "government", "trusted_news"),
        (
            "get_company_context",
            "get_fundamentals",
            "get_filings",
            "get_events",
            "get_policy_actions",
            "get_macro_trends",
            "get_market_history",
            "get_mechanism_paths",
            "get_backtest_results",
        ),
        ("interest_margin", "financing_cost", "credit_demand", "currency_translation", "liquidity"),
    ),
    _expert(
        "expert.defense_geopolitics",
        "Defense & Geopolitics Expert",
        "defense_geopolitics",
        ("company", "country", "government", "sector"),
        ("official", "filing", "government", "trusted_news", "fused_claim"),
        (
            "get_company_context",
            "get_filings",
            "get_events",
            "get_policy_actions",
            "get_fused_claims",
            "get_source_reputation",
            "get_geopolitical_events",
            "get_mechanism_paths",
            "get_backtest_results",
        ),
        ("defense_procurement", "supply_chain", "export_restriction", "sanctions", "risk_premium"),
    ),
    _expert(
        "expert.energy",
        "Energy Expert",
        "energy",
        ("company", "commodity", "sector", "country"),
        ("official", "filing", "government", "trusted_news"),
        (
            "get_company_context",
            "get_fundamentals",
            "get_filings",
            "get_events",
            "get_policy_actions",
            "get_macro_trends",
            "get_geopolitical_events",
            "get_market_history",
            "get_mechanism_paths",
            "get_backtest_results",
        ),
        ("energy_cost", "supply_disruption", "commodity_exposure", "infrastructure"),
    ),
)

EXPERTS_BY_ID = {item.expert_id: item for item in FIXED_EXPERTS}

CHECKLISTS = {
    "technology_ai": (
        "revenue growth",
        "margins",
        "capex",
        "R&D",
        "customer concentration",
        "cloud demand",
        "semiconductor cycle",
        "regulation",
        "moat evidence",
    ),
    "israel_real_estate": (
        "debt profile",
        "rate sensitivity",
        "occupancy",
        "pipeline",
        "housing policy",
        "construction labor",
        "input costs",
        "geography",
        "demand",
    ),
    "banking_macro": ("rates", "inflation", "credit", "FX", "margins", "liquidity", "policy"),
    "defense_geopolitics": (
        "procurement",
        "spending",
        "disruption",
        "supply chain",
        "export restrictions",
        "sanctions",
        "reserve effects",
    ),
    "energy": ("oil and gas", "electricity", "costs", "regulation", "disruption", "infrastructure"),
    "general": ("evidence", "counterevidence", "mechanisms", "horizons", "uncertainties"),
}
